services:
  evolution_api:
    image: atendai/evolution-api:v2.1.1
    container_name: evolution_api
    restart: always
    ports:
      - "8085:8080"
    environment:
      - SERVER_URL=http://localhost:8085
      - AUTHENTICATION_API_KEY=123456
      - DATABASE_ENABLED=false # Usando Supabase como banco principal via app
      - STORE_MESSAGES=false
      - STORE_MESSAGE_UPSET=false
      - STORE_GROUP_INFO=false
      - STORE_CONTACTS=false
      - STORE_CHATS=false
    volumes:
      - evolution_instances:/evolution/instances

volumes:
  evolution_instances:
